stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  before_script:
    - 'which ssh-agent || (apk add --update openssh-client)'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_SSH_PRIVATE_KEY" | sed 's/\r$//' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config
    - ssh-keyscan -H 5.161.187.6 >> ~/.ssh/known_hosts
  script:
    - ssh -vvv root@5.161.187.6 "echo 'SSH connection successful'"
    - ssh root@5.161.187.6 "mkdir -p /root/.ssh && echo '$DEPLOY_SSH_PRIVATE_KEY' > /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa"
    - ssh root@5.161.187.6 "cd /root/y-landing && git pull origin main"
    - ssh root@5.161.187.6 "cd /root/y-landing && sudo docker-compose down"
    - ssh root@5.161.187.6 "cd /root/y-landing && sudo docker-compose up --build -d"
    - ssh root@5.161.187.6 "docker ps"